spring:
  application:
    name:
      weather
  datasource:
    url: jdbc:h2:mem:weather;mode=oracle
    username: tiila
    password: tiila
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
