DROP TABLE IF EXISTS CITY;
Create table CITY(ID VARCHAR(22),NAME VARCHAR(22),ZIPCODE NUMBER(22),REGION VARCHAR(22),COUNTRY VARCHAR(22),LONGITUDE NUMBER(8),LATITUDE NUMBER(8));
INSERT INTO city (ID,NAME,ZIPCODE,REGION,COUNTRY,LONGITUDE,LATITUDE) VALUES ('1', 'Brest', '29200', 'Bretagne', 'France',100,100);